services:
  - type: web
    name: pdf-rag-client
    env: docker
    dockerfilePath: ./client/Dockerfile
    plan: free
    envVars:
      - key: NEXT_PUBLIC_API_URL
        value: https://pdf-rag-server.onrender.com
    autoDeploy: true

  - type: web
    name: pdf-rag-server
    env: docker
    dockerfilePath: ./server/Dockerfile
    plan: free
    envVars:
      - key: API_KEY
        sync: false
      - key: QDRANT_URL
        value: http://qdrant:6333
      - key: REDIS_HOST
        value: valkey
      - key: REDIS_PORT
        value: 6379
    autoDeploy: true

  - type: worker
    name: qdrant
    env: docker
    dockerfilePath: ./docker/qdrant.Dockerfile
    plan: free
    autoDeploy: false

  - type: worker
    name: valkey
    env: docker
    dockerfilePath: ./docker/valkey.Dockerfile
    plan: free
    autoDeploy: false
